spring:
  application:
    name: fridge
  datasource:
    url: jdbc:postgresql://postgres:5432/db
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true

logging:
  level:
    org.springframework: DEBUG
    org.springframework.boot: DEBUG
    org.springframework.cloud: DEBUG
    org.postgresql: DEBUG

server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery:8761/eureka/